#ifndef BLOCKLISTMANAGER_GLOBAL_H
#define BLOCKLISTMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BLOCKLISTMANAGER_LIBRARY)
#  define BLOCKLISTMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define BLOCKLISTMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // BLOCKLISTMANAGER_GLOBAL_H
