#ifndef SLOPECRAFT_UTILITIES_LIBSCGUI_LIBSCGUI_H
#define SLOPECRAFT_UTILITIES_LIBSCGUI_LIBSCGUI_H

#include <libAbstractGUI.h>

namespace libSCGUI {} // namespace libSCGUI

#endif // SLOPECRAFT_UTILITIES_LIBSCGUI_LIBSCGUI_H